# Generated by Django 5.0.1 on 2024-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesprediction',
            name='age',
            field=models.FloatField(default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='blood_pressure',
            field=models.FloatField(default=0, verbose_name='Blood Pressure'),
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='bmi',
            field=models.FloatField(default=0, verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='diabetes_pedigree_function',
            field=models.FloatField(default=0, verbose_name='Diabetes Pedigree Function'),
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='insulin',
            field=models.FloatField(default=0, verbose_name='Insulin'),
        ),
        migrations.AddField(
            model_name='diabetesprediction',
            name='skin_thickness',
            field=models.FloatField(default=0, verbose_name='Skin Thickness'),
        ),
        migrations.AlterField(
            model_name='diabetesprediction',
            name='glucose',
            field=models.FloatField(default=0, verbose_name='Glucose'),
        ),
        migrations.AlterField(
            model_name='diabetesprediction',
            name='pregnancies',
            field=models.FloatField(default=0, verbose_name='Pregnancies'),
        ),
    ]
