# Generated by Django 5.0.1 on 2024-03-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_diabetesprediction_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='movements_per_hour',
            field=models.FloatField(default=0.0, verbose_name='Movements per hour'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='regularity',
            field=models.FloatField(default=0.0, verbose_name='Regularity'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='snore_time',
            field=models.FloatField(default=0.0, verbose_name='Snore time'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='steps',
            field=models.FloatField(default=0.0, verbose_name='Steps'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='time_asleep_seconds',
            field=models.FloatField(default=0.0, verbose_name='Time asleep (seconds)'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='time_before_sleep_seconds',
            field=models.FloatField(default=0.0, verbose_name='Time before sleep (seconds)'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='time_in_bed_seconds',
            field=models.FloatField(default=0.0, verbose_name='Time in bed (seconds)'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='window_start',
            field=models.FloatField(default=0.0, verbose_name='Window start'),
        ),
        migrations.AddField(
            model_name='sleepcycleprediction',
            name='window_stop',
            field=models.FloatField(default=0.0, verbose_name='Window stop'),
        ),
        migrations.AlterField(
            model_name='sleepcycleprediction',
            name='end',
            field=models.FloatField(default=0.0, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='sleepcycleprediction',
            name='start',
            field=models.FloatField(default=0.0, verbose_name='Start'),
        ),
    ]
